# Generated by Django 2.2.6 on 2019-10-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estabelecimento',
            new_name='Establishment',
        ),
        migrations.AlterModelTable(
            name='establishment',
            table='establishment',
        ),
    ]
