# Generated by Django 2.2.6 on 2019-10-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191015_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='dist',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
