# Generated by Django 2.2.6 on 2019-10-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_establishment_dist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='dist',
            field=models.CharField(default='', max_length=200),
        ),
    ]
