# Generated by Django 2.2.6 on 2019-10-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191015_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='dist',
        ),
    ]
